### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Kingtonberry** [Ccode-lang/LethalSirenHead#6]
Is it possible to prevent the SirenHead from walking through the ship? Currently it just phases through it like it's not there. Besides that I'm loving the mod so far. Thank you

**Comment by Roobotics** [comment]
Same primary issue, folks I was hosting for agree that it repeatedly violating the safe-space of the ship is an automatic no-go for including it in packs currently. Also the radio-chatter effect it causes(I presume that's one of the things it does) is **very** loud compared to anything else.

Would be really interesting if it being spawned, could hook into skinwalkers and play older clips across the radios and/or deafen all radio broadcasts to disorient the team instead of annoy them with harsh noises they know nobody is making.(but the idea that noises could get them killed to eyeless dogs in itself, is a good aspect still!)

**Comment by Ccode-lang** [comment]
These are both great requests. I'm currently working on fixing the hitbox to make him not enter the ship. I could also turn the radio sounds down significantly for the other problem.

**Comment by Ccode-lang** [comment]
Both of these should be fixed with the newest thunderstore release now.

**Comment by Roobotics** [comment]
Awesome! We'll give it another try again and see how the changes play out!

Also another thing which might just be an incompatibility with 'LethalResonance', I've never heard the siren or alert noises when around it..? or should that only be if it's aware/chasing someone?(It never noticed us, so was stomping around only) I've not experienced audio issues in other custom mobs, but if it needs to broadcast on a more global channel, maybe something is incompatible there, just fyi.

**Comment by CptRazor** [comment]
The siren head for me does seem to have collisions with the ship now except he walks straight into the ship through the doors now as well. Would be cool if there was some behavior for reaching into the ship after the player? Always thought that would be interesting with the forest keepers as well if you don't shut the doors in time. I used ChatCommands by CTMods to spawn Siren head in to show it walking into the ship.

![image](https://github.com/Ccode-lang/LethalSirenHead/assets/162824356/ce122150-5f24-418c-b76b-ef2139964888)

**Comment by Ccode-lang** [comment]
For lethal resonance, I wasn't thinking about it when I made the mod so possibly there is something there. I think I also know why he walks into the ship now, so that should be fixed soon along with a few AI problems.

**Comment by Ccode-lang** [comment]
He shouldn't walk into the ship for real now this time.
